<?php
//
// File generated by ... on the 2016-03-09T16:20:47+0100
// Please do not edit manually
//

/**
 * Classes and menus for esguardian-config-mgmt (version 1.0.0)
 *
 * @author      iTop compiler
 * @license     http://opensource.org/licenses/AGPL-3.0
 */



class ESGuardianFileStore extends SoftwareInstance
{
	public static function Init()
	{
		$aParams = array
		(
			'category' => 'bizmodel,searchable',
			'key_type' => 'autoincrement',
			'name_attcode' => array('name', 'system_name'),
			'state_attcode' => '',
			'reconc_keys' => array('name', 'org_id', 'organization_name', 'system_id', 'system_name'),
			'db_table' => 'esguardianfilestore',
			'db_key_field' => 'id',
			'db_finalclass_field' => '',
		);
		MetaModel::Init_Params($aParams);
		MetaModel::Init_InheritAttributes();



		MetaModel::Init_SetZListItems('details', array (
  0 => 'name',
  1 => 'org_id',
  2 => 'status',
  3 => 'business_criticity',
  4 => 'system_id',
  5 => 'path',
  6 => 'move2production',
  7 => 'description',
  8 => 'contacts_list',
  9 => 'documents_list',
  10 => 'applicationsolution_list',
));
		MetaModel::Init_SetZListItems('standard_search', array (
  0 => 'name',
  1 => 'org_id',
  2 => 'business_criticity',
  3 => 'move2production',
));
		MetaModel::Init_SetZListItems('list', array (
  0 => 'name',
  1 => 'system_id',
  2 => 'org_id',
  3 => 'business_criticity',
));

	}


}